stages:
  - test
  - deploy

hello-ci:
  stage: test
  script:
    - echo "Hello from GitLab CI!"
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Pipeline ID $CI_PIPELINE_ID"
  stage: deploy
  script: 
   - echo "sang step 2"
